=== Kristine1975/Rezilla/RezillaExtras/Xml/aete.dtd
<!-- This is a preliminary draft version! -->
<!--
 |                          Created : 2002-01-02 18:04:05
 |                Last modification : 2002-01-02 19:15:31
 | Author : Bernard Desgraupes
 | e-mail : bdesgraupes@easyconnect.fr
 | web : http://webperso.easyconnect.fr/bdesgraupes/
 | Description : DTD to formalize the  structure  of  an  aete  (Apple  Events
 | Terminology) resource. The format for  'aete'  resources  is  described  in
 | "Apple Event Terminology Resources".
 | See
 | /Technical Publications/mac/pdf/Interapplication_Communication/AE_Term_Resources.pdf
-->

<!ELEMENT AETEREZ (
		aeteRezNum,
		aeteRezTitle,
		MajorVersion,
		MinorVersion,
		LanguageCode,
		ScriptCode,
		ArraySuites
		)
>

<!ELEMENT ArraySuites (Suite)+>
<!ELEMENT Suite (ArrayEvents, ArrayClasses, ArrayComparisonOps, ArrayEnumerations)>
<!ELEMENT ArrayEvents (Event*)>
<!ELEMENT ArrayClasses (Class*)>
<!ELEMENT ArrayComparisonOps (ComparisonOp*)>
<!ELEMENT ArrayEnumerations (Enumeration*)>

<!ELEMENT Event (
		    EventName, 
		    EventDescription, 
		    EventClass, EventClass, 
		    ReplyDirectParamType, 
		    ReplyDirectParamDescription,
		    IsReplyRequired,
		    IsReplyList,
		    IsReplyEnumerated,
		    HasTightBindingPrecedence,
		    EnumConstantOrType,
		    CanEnumListRepeat,
		    ReplyIsValueOrRef,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved,
		    IsVerbEvent,
		    Reserved,
		    Reserved,
		    Reserved,
		    DirectParamType,
		    DirectParmDescription,
		    IsDirectParamRequired,
		    IsDirectParamList,
		    IsDirectParamEnumerated,
		    ChangeState,
		    EnumConstantOrType,
		    CanEnumListRepeat,
		    DirectParamIsValueOrRef,
		    IsDirectParamTarget,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved,
		    ArrayOtherParams
		    )
>

<!ELEMENT ArrayOtherParams (OtherParam*)>
<!ELEMENT OtherParam (
		    OtherParamName,
		    OtherParamKeyword,
		    OtherParamType,
		    OtherParamDescription,
		    IsOtherParamRequired,
		    IsOtherParamList,
		    IsOtherParamEnumerated,
		    Reserved,
		    EnumConstantOrType,
		    CanEnumListRepeat,
		    OtherParamIsValueOrRef,
		    IsOtherParamTarget,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved,
		    PrepositionOrLabeled,
		    IsFeminine,
		    IsMasculine,
		    SingularOrPlural
		    )
>

<!ELEMENT Class (
		    ClassName,
		    ClassID,
		    ClassDescription,
		    ArrayProperties, 
		    ArrayElements
		    )
>

<!ELEMENT ArrayProperties (ClassProperty*)>
<!ELEMENT ClassProperty (
		    PropertyName,
		    PropertyID,
		    PropertyClass,
		    PropertyDescription,
		    Reserved,
		    IsPropertyList,
		    IsPropertyEnumerated,
		    IsReadOnlyProperty,
		    EnumConstantOrType,
		    CanEnumListRepeat,
		    PropertyIsValueOrRef,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved,
		    IsApostrophe,
		    IsFeminine,
		    IsMasculine,
		    SingularOrPlural
		    )
>


<!ELEMENT ArrayElements (ClassElement*)>
<!ELEMENT ClassElement (
		    ClassElementID,
		    ArrayKeyForms
		    )
>

<!ELEMENT ArrayKeyForms (KeyFormID)*>

<!ELEMENT ComparisonOp (
		    ComparisonOpName,
		    ComparisonOpID,
		    ComparisonOpDescription
		    )
>

<!ELEMENT Enumeration (
		    EnumerationID,
		    ArrayEnumerators
		    )
>

<!ELEMENT ArrayEnumerators (Enumerator)*>
<!ELEMENT Enumerator (
		    EnumeratorName,
		    EnumeratorID,
		    EnumeratorDescription
		    )
>

<!-- ==================================================================== -->
<!--                       Atomic elements                                -->
<!-- ==================================================================== -->
<!--Boolean-->
<!ELEMENT CanEnumListRepeat (enumListCanRepeat|enumListIsExclusive)>
<!ELEMENT ChangeState (doesntChangeState|changesState)>
<!ELEMENT DirectParamIsValueOrRef (directParamIsValue|directParamIsReference)>
<!ELEMENT EnumsAre (enumsAreConstants|enumsAreTypes)>
<!ELEMENT HasTightBindingPrecedence (notTightBindingFunction|tightBindingFunction)>
<!ELEMENT IsApostrophe (noApostrophe|apostrophe)>
<!ELEMENT IsDirectParamEnumerated (notEnumerated|enumerated)>
<!ELEMENT IsDirectParamList (singleItem|listOfItems)>
<!ELEMENT IsDirectParamRequired (directParamRequired|directParamOptional)>
<!ELEMENT IsDirectParamTarget (directParamIsTarget|notDirectParamIsTarget)>
<!ELEMENT IsFeminine (notFeminine|feminine)>
<!ELEMENT IsMasculine (notMasculine|masculine)>
<!ELEMENT IsOtherParamEnumerated (notEnumerated|enumerated)>
<!ELEMENT IsOtherParamList (singleItem|listOfItems)>
<!ELEMENT IsOtherParamRequired (required|optional)>
<!ELEMENT IsOtherParamTarget (notParamIsTarget|paramIsTarget)>
<!ELEMENT IsPropertyEnumerated (notEnumerated|enumerated)>
<!ELEMENT IsPropertyList (singleItem|listOfItems)>
<!ELEMENT IsReadOnlyProperty (readOnly|readWrite)>
<!ELEMENT IsReplyEnumerated (notEnumerated|enumerated)>
<!ELEMENT IsReplyList (singleItem|listOfItems)>
<!ELEMENT IsReplyRequired (replyRequired|replyOptional)>
<!ELEMENT IsVerbEvent (verbEvent|nonVerbEvent)>
<!ELEMENT OtherParamIsValueOrRef (paramIsValue|paramIsReference)>
<!ELEMENT PrepositionOrLabeled (prepositionParam|labeledParam)>
<!ELEMENT PropertyIsValueOrRef (propertyIsValue|propertyIsReference)>
<!ELEMENT ReplyIsValueOrRef (replyIsValue|replyIsReference)>
<!ELEMENT SingularOrPlural (singular|plural)>


<!--String-->
<!ELEMENT aeteRezTitle (#PCDATA)>
<!ELEMENT ClassDescription (#PCDATA)>
<!ELEMENT ComparisonOpDescription (#PCDATA)>
<!ELEMENT ComparisonOpName (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT DirectParmDescription (#PCDATA)>
<!ELEMENT EnumeratorDescription (#PCDATA)>
<!ELEMENT EnumeratorName (#PCDATA)>
<!ELEMENT EventDescription (#PCDATA)>
<!ELEMENT EventName (#PCDATA)>
<!ELEMENT OtherParamDescription (#PCDATA)>
<!ELEMENT OtherParamName (#PCDATA)>
<!ELEMENT PropertyDescription (#PCDATA)>
<!ELEMENT PropertyName (#PCDATA)>
<!ELEMENT ReplyDirectParamDescription (#PCDATA)>
<!ELEMENT SuiteName (#PCDATA)>
<!ELEMENT SuiteDescription (#PCDATA)>

<!--Four char codes-->
<!ELEMENT ObjectClassID (#PCDATA)>
<!ELEMENT ClassElementID (#PCDATA)>
<!ELEMENT ComparisonOpID (#PCDATA)>
<!ELEMENT DirectParamType (#PCDATA)>
<!ELEMENT EnumerationID (#PCDATA)>
<!ELEMENT EnumeratorID (#PCDATA)>
<!ELEMENT EventClass (#PCDATA)>
<!ELEMENT EventID (#PCDATA)>
<!ELEMENT KeyFormID (#PCDATA)>
<!ELEMENT OtherParamKeyword (#PCDATA)>
<!ELEMENT OtherParamType (#PCDATA)>
<!ELEMENT PropertyClass (#PCDATA)>
<!ELEMENT PropertyID (#PCDATA)>
<!ELEMENT ReplyDirectParamType (#PCDATA)>
<!ELEMENT SuiteID (#PCDATA)>

<!--integer-->
<!ELEMENT aeteRezNum (integer)>
<!ELEMENT LanguageCode (integer)>
<!ELEMENT ScriptCode (integer)>
<!ELEMENT SuiteLevel (integer)>
<!ELEMENT SuiteVersion (integer)>

<!--hex byte-->
<!ELEMENT MajorVersion (#PCDATA)>
<!ELEMENT MinorVersion (#PCDATA)>


<!ELEMENT Reserved EMPTY >
<!ELEMENT true EMPTY >
<!ELEMENT false EMPTY >
<!ELEMENT bool (true|false) >
<!ELEMENT integer (#PCDATA)>

<!ELEMENT enumListCanRepeat (false)>
<!ELEMENT doesntChangeState (false)>
<!ELEMENT directParamIsValue (false)>
<!ELEMENT enumsAreConstants (false)>
<!ELEMENT notTightBindingFunction (false)>
<!ELEMENT noApostrophe (false)>
<!ELEMENT notEnumerated (false)>
<!ELEMENT singleItem (false)>
<!ELEMENT directParamRequired (false)>
<!ELEMENT directParamIsTarget (false)>
<!ELEMENT notFeminine (false)>
<!ELEMENT notMasculine (false)>
<!ELEMENT notEnumerated (false)>
<!ELEMENT singleItem (false)>
<!ELEMENT required (false)>
<!ELEMENT notParamIsTarget (false)>
<!ELEMENT notEnumerated (false)>
<!ELEMENT singleItem (false)>
<!ELEMENT readOnly (false)>
<!ELEMENT notEnumerated (false)>
<!ELEMENT singleItem (false)>
<!ELEMENT replyRequired (false)>
<!ELEMENT verbEvent (false)>
<!ELEMENT paramIsValue (false)>
<!ELEMENT prepositionParam (false)>
<!ELEMENT propertyIsValue (false)>
<!ELEMENT replyIsValue (false)>
<!ELEMENT singular (false)>

<!ELEMENT enumListIsExclusive (true)>
<!ELEMENT changesState (true)>
<!ELEMENT directParamIsReference (true)>
<!ELEMENT enumsAreTypes (true)>
<!ELEMENT tightBindingFunction (true)>
<!ELEMENT apostrophe (true)>
<!ELEMENT enumerated (true)>
<!ELEMENT listOfItems (true)>
<!ELEMENT directParamOptional (true)>
<!ELEMENT notDirectParamIsTarget (true)>
<!ELEMENT feminine (true)>
<!ELEMENT masculine (true)>
<!ELEMENT enumerated (true)>
<!ELEMENT listOfItems (true)>
<!ELEMENT optional (true)>
<!ELEMENT paramIsTarget (true)>
<!ELEMENT enumerated (true)>
<!ELEMENT listOfItems (true)>
<!ELEMENT readWrite (true)>
<!ELEMENT enumerated (true)>
<!ELEMENT listOfItems (true)>
<!ELEMENT replyOptional (true)>
<!ELEMENT nonVerbEvent (true)>
<!ELEMENT paramIsReference (true)>
<!ELEMENT labeledParam (true)>
<!ELEMENT propertyIsReference (true)>
<!ELEMENT replyIsReference (true)>
<!ELEMENT plural (true)>

=== Kristine1975/Rezilla/RezillaExtras/AppleScript/Terminology/Rezilla_aete.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This is a preliminary draft version! -->
<!-- Rezilla project -->
<!-- Author: Bernard Desgraupes -->
<!-- E-mail: bdesgraupes@users.sourceforge.net -->
<!-- Web: http://webperso.easyconnect.fr/bdesgraupes/rezilla.html -->
<!-- $Revision$ -->
<!-- $Date$ -->
<!DOCTYPE AETEREZ SYSTEM "file://localhost/System/Library/DTDs/aete.dtd">

<AETEREZ>
<aeteRezNum>0</aeteRezNum>
<aeteRezTitle>Scripting terminology</aeteRezTitle>
<MajorVersion>0x1</MajorVersion>
<MinorVersion>0x0</MinorVersion>
<LanguageCode>0</LanguageCode>
<ScriptCode>0</ScriptCode>

<ArraySuites>
	<Suite>
	<SuiteName>Required Suite</SuiteName>       	
	<SuiteDescription>Terms that every application should support</SuiteDescription>	
	<SuiteID>reqd</SuiteID>         	
	<SuiteLevel>1</SuiteLevel>      	
	<SuiteVersion>1</SuiteVersion>    
		<ArrayEvents>
		</ArrayEvents>

		<ArrayClasses>
		</ArrayClasses>

		<ArrayComparisonOps>
		</ArrayComparisonOps>

		<ArrayEnumerations>
		</ArrayEnumerations>
	</Suite>

	<Suite>
	<SuiteName>Standard Suite</SuiteName>
	<SuiteDescription>Common terms for most applications</SuiteDescription>
	<SuiteID>CoRe</SuiteID>
	<SuiteLevel>1</SuiteLevel>
	<SuiteVersion>1</SuiteVersion>
		<ArrayEvents>
			<Event>
				<EventName>close</EventName>
				<EventDescription>Close an object</EventDescription>
				<EventClass>core</EventClass>
				<EventID>clos</EventID>
				<ReplyDirectParamType>null</ReplyDirectParamType>
				<ReplyDirectParamDescription></ReplyDirectParamDescription>
				<IsReplyRequired>replyOptional</IsReplyRequired>
				<IsReplyList>singleItem</IsReplyList>
				<IsReplyEnumerated>notEnumerated</IsReplyEnumerated>
				<HasTightBindingPrecedence>notTightBindingFunction</HasTightBindingPrecedence>
				<EnumConstantOrType>enumsAreConstants</EnumConstantOrType>
				<CanEnumListRepeat>enumListCanRepeat</CanEnumListRepeat>
				<ReplyIsValueOrRef>replyIsValue</ReplyIsValueOrRef>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<IsVerbEvent>verbEvent</IsVerbEvent>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<DirectParamType>obj </DirectParamType>
				<DirectParmDescription>the objects to close</DirectParmDescription>
				<IsDirectParamRequired>directParamRequired</IsDirectParamRequired>
				<IsDirectParamList>singleItem</IsDirectParamList>
				<IsDirectParamEnumerated>notEnumerated</IsDirectParamEnumerated>
				<ChangeState>changesState</ChangeState>
				<EnumConstantOrType>enumsAreConstants</EnumConstantOrType>
				<CanEnumListRepeat>enumListCanRepeat</CanEnumListRepeat>
				<DirectParamIsValueOrRef>directParamIsValue</DirectParamIsValueOrRef>
				<IsDirectParamTarget>directParamIsTarget</IsDirectParamTarget>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<ArrayOtherParams>
					<OtherParam>
						<OtherParamName>saving</OtherParamName>
						<OtherParamKeyword>savo</OtherParamKeyword>
						<OtherParamType>savo</OtherParamType>
						<OtherParamDescription>specifies whether or not changes should be saved before closing</OtherParamDescription>
						<IsOtherParamRequired>optional</IsOtherParamRequired>
						<IsOtherParamList>singleItem</IsOtherParamList>
						<IsOtherParamEnumerated>enumerated</IsOtherParamEnumerated>
						<Reserved/>
						<EnumConstantOrType>enumsAreConstants</EnumConstantOrType>
						<CanEnumListRepeat>enumListCanRepeat</CanEnumListRepeat>
						<OtherParamIsValueOrRef>paramIsValue</OtherParamIsValueOrRef>
						<IsOtherParamTarget>notParamIsTarget</IsOtherParamTarget>
						<Reserved/>
						<Reserved/>
						<Reserved/>
						<Reserved/>
						<PrepositionOrLabeled>prepositionParam</PrepositionOrLabeled>
						<IsFeminine>notFeminine</IsFeminine>
						<IsMasculine>notMasculine</IsMasculine>
						<SingularOrPlural>singular</SingularOrPlural>
					</OtherParam>
					<OtherParam>
						<OtherParamName>in</OtherParamName>
						<OtherParamKeyword>kfil</OtherParamKeyword>
						<OtherParamType>alis</OtherParamType>
						<OtherParamDescription>the file in which to save the object</OtherParamDescription>
						<IsOtherParamRequired>optional</IsOtherParamRequired>
						<IsOtherParamList>singleItem</IsOtherParamList>
						<IsOtherParamEnumerated>notEnumerated</IsOtherParamEnumerated>
						<Reserved/>
						<EnumConstantOrType>enumsAreConstants</EnumConstantOrType>
						<CanEnumListRepeat>enumListCanRepeat</CanEnumListRepeat>
						<OtherParamIsValueOrRef>paramIsValue</OtherParamIsValueOrRef>
						<IsOtherParamTarget>notParamIsTarget</IsOtherParamTarget>
						<Reserved/>
						<Reserved/>
						<Reserved/>
						<Reserved/>
						<PrepositionOrLabeled>prepositionParam</PrepositionOrLabeled>
						<IsFeminine>notFeminine</IsFeminine>
						<IsMasculine>notMasculine</IsMasculine>
						<SingularOrPlural>singular</SingularOrPlural>
					</OtherParam>
				</ArrayOtherParams>
			</Event>

			<Event>
				<EventName>count</EventName>
				<EventDescription>Return the number of elements of a particular class within an object</EventDescription>
				<EventClass>core</EventClass>
				<EventID>cnte</EventID>
				<ReplyDirectParamType>long</ReplyDirectParamType>
				<ReplyDirectParamDescription>the number of elements</ReplyDirectParamDescription>
				<IsReplyRequired>replyRequired</IsReplyRequired>
				<IsReplyList>singleItem</IsReplyList>
				<IsReplyEnumerated>notEnumerated</IsReplyEnumerated>
				<HasTightBindingPrecedence>notTightBindingFunction</HasTightBindingPrecedence>
				<EnumConstantOrType>enumsAreConstants</EnumConstantOrType>
				<CanEnumListRepeat>enumListCanRepeat</CanEnumListRepeat>
				<ReplyIsValueOrRef>replyIsValue</ReplyIsValueOrRef>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<IsVerbEvent>verbEvent</IsVerbEvent>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<DirectParamType>obj </DirectParamType>
				<DirectParmDescription>the object whose elements are to be counted</DirectParmDescription>
				<IsDirectParamRequired>directParamRequired</IsDirectParamRequired>
				<IsDirectParamList>singleItem</IsDirectParamList>
				<IsDirectParamEnumerated>notEnumerated</IsDirectParamEnumerated>
				<ChangeState>doesntChangeState</ChangeState>
				<EnumConstantOrType>enumsAreConstants</EnumConstantOrType>
				<CanEnumListRepeat>enumListCanRepeat</CanEnumListRepeat>
				<DirectParamIsValueOrRef>directParamIsValue</DirectParamIsValueOrRef>
				<IsDirectParamTarget>directParamIsTarget</IsDirectParamTarget>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<ArrayOtherParams>
					<OtherParam>
						<OtherParamName>each</OtherParamName>
						<OtherParamKeyword>kocl</OtherParamKeyword>
						<OtherParamType>type</OtherParamType>
						<OtherParamDescription>the class of the elements to be counted</OtherParamDescription>
						<IsOtherParamRequired>required</IsOtherParamRequired>
						<IsOtherParamList>singleItem</IsOtherParamList>
						<IsOtherParamEnumerated>notEnumerated</IsOtherParamEnumerated>
						<Reserved/>
						<EnumConstantOrType>enumsAreConstants</EnumConstantOrType>
						<CanEnumListRepeat>enumListCanRepeat</CanEnumListRepeat>
						<OtherParamIsValueOrRef>paramIsValue</OtherParamIsValueOrRef>
						<IsOtherParamTarget>notParamIsTarget</IsOtherParamTarget>
						<Reserved/>
						<Reserved/>
						<Reserved/>
						<Reserved/>
						<PrepositionOrLabeled>prepositionParam</PrepositionOrLabeled>
						<IsFeminine>notFeminine</IsFeminine>
						<IsMasculine>notMasculine</IsMasculine>
						<SingularOrPlural>singular</SingularOrPlural>
					</OtherParam>
				</ArrayOtherParams>
			</Event>

			<Event>
				<EventName>data size</EventName>
				<EventDescription>Return the size in bytes of an object</EventDescription>
				<EventClass>core</EventClass>
				<EventID>dsiz</EventID>
				<ReplyDirectParamType>long</ReplyDirectParamType>
				<ReplyDirectParamDescription>the size of the object in bytes</ReplyDirectParamDescription>
				<IsReplyRequired>replyRequired</IsReplyRequired>
				<IsReplyList>singleItem</IsReplyList>
				<IsReplyEnumerated>notEnumerated</IsReplyEnumerated>
				<HasTightBindingPrecedence>notTightBindingFunction</HasTightBindingPrecedence>
				<EnumConstantOrType>enumsAreConstants</EnumConstantOrType>
				<CanEnumListRepeat>enumListCanRepeat</CanEnumListRepeat>
				<ReplyIsValueOrRef>replyIsValue</ReplyIsValueOrRef>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<IsVerbEvent>verbEvent</IsVerbEvent>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<DirectParamType>obj </DirectParamType>
				<DirectParmDescription>the object whose data size is to be returned</DirectParmDescription>
				<IsDirectParamRequired>directParamRequired</IsDirectParamRequired>
				<IsDirectParamList>singleItem</IsDirectParamList>
				<IsDirectParamEnumerated>notEnumerated</IsDirectParamEnumerated>
				<ChangeState>doesntChangeState</ChangeState>
				<EnumConstantOrType>enumsAreConstants</EnumConstantOrType>
				<CanEnumListRepeat>enumListCanRepeat</CanEnumListRepeat>
				<DirectParamIsValueOrRef>directParamIsValue</DirectParamIsValueOrRef>
				<IsDirectParamTarget>directParamIsTarget</IsDirectParamTarget>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<Reserved/>
				<ArrayOtherParams>
				</ArrayOtherParams>
			</Event>

			<Event>
				<EventName>exists</EventName>
				<EventDescription>Verify if an object exists</EventDescription>
				<EventClass>core</EventClass>
				<EventID>doex</EventID>
				<ReplyDirectParamType>bool</ReplyDirectParamType>
				<ReplyDirectParamDescription>true if it exists, false if not</ReplyDirectParamDescription>
				<IsReplyRequired>replyRequired</IsReplyRequired>
				<IsReplyList>singleItem</IsReplyList>
				<IsReplyEnumerated>notEnumerated</IsReplyEnumerated>
