=== Kristine1975/Rezilla/trunk/RezillaExtras/Xml/aete.dtd
<!-- This is a preliminary draft version! -->
<!--
 |                          Created : 2002-01-02 18:04:05
 |                Last modification : 2005-02-19 16:39:03
 | Author : Bernard Desgraupes
 | e-mail : bdesgraupes@easyconnect.fr
 | web : http://webperso.easyconnect.fr/bdesgraupes/
 | Description : DTD to formalize the structure of an aete (Apple Events
 | Terminology) resource. The format for 'aete' resources is described in
 | "Apple Event Terminology Resources".
 | See
 | /Technical Publications/mac/pdf/Interapplication_Communication/AE_Term_Resources.pdf
 | 
 | (bd 2005-02-19) Removed AeteResID and AeteResTitle
 | 
 | Version 1.2
-->


<!ELEMENT AeteResource (
		MajorVersion,
		MinorVersion,
		LanguageCode,
		ScriptCode,
		ArraySuites
		)
>

<!ELEMENT ArraySuites (Suite)+>
<!ELEMENT Suite (SuiteName, SuiteDescription, SuiteID, SuiteLevel, SuiteVersion, 
		ArrayEvents, ArrayClasses, ArrayComparisonOps, ArrayEnumerations)>
<!ELEMENT ArrayEvents (Event*)>
<!ELEMENT ArrayClasses (Class*)>
<!ELEMENT ArrayComparisonOps (ComparisonOp*)>
<!ELEMENT ArrayEnumerations (Enumeration*)>

<!ELEMENT Event (
		    EventName, 
		    EventDescription, 
		    EventClass, 
		    EventID, 
		    ReplyType, 
		    ReplyDescription,
		    ReplyFlags,
		    DirectParamType,
		    DirectParamDescription,
		    DirectFlags,
		    ArrayOtherParams
		)
>

<!ELEMENT ReplyFlags (
		    IsOptional,
		    IsListOfItems,
		    IsEnumerated,
		    TightBindingFunction,
		    EnumsAreTypes,
		    EnumIsExclusive,
		    ReplyIsReference,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved,
		    NonVerbEvent,
		    Reserved,
		    Reserved,
		    Reserved
		    )
>

<!ELEMENT DirectFlags (
		    IsOptional,
		    IsListOfItems,
		    IsEnumerated,
		    ChangeState,
		    EnumsAreTypes,
		    EnumIsExclusive,
		    DirectParamIsReference,
		    NotDirectParamIsTarget,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved
		    )
>


<!ELEMENT ArrayOtherParams (Parameter*)>
<!ELEMENT Parameter (
		    ParameterName,
		    ParameterID,
		    ParameterType,
		    ParameterDescription,
		    ParameterFlags
		    )
>

<!ELEMENT ParameterFlags (
		    IsOptional,
		    IsListOfItems,
		    IsEnumerated,
		    Reserved,
		    EnumsAreTypes,
		    EnumIsExclusive,
		    ParamIsReference,
		    ParamIsTarget,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved,
		    LabeledParam,
		    IsFeminine,
		    IsMasculine,
		    Plural
		    )
>


<!ELEMENT Class (
		    ClassName,
		    ClassID,
		    ClassDescription,
		    ArrayProperties, 
		    ArrayElements
		    )
>

<!ELEMENT ArrayProperties (Property*)>
<!ELEMENT Property (
		    PropertyName,
		    PropertyID,
		    PropertyClass,
		    PropertyDescription,
		    PropertyFlags
		    )
>

<!ELEMENT PropertyFlags (
		    Reserved,
		    IsListOfItems,
		    IsEnumerated,
		    IsReadWrite,
		    EnumsAreTypes,
		    EnumIsExclusive,
		    PropertyIsReference,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved,
		    Reserved,
		    IsApostrophe,
		    IsFeminine,
		    IsMasculine,
		    Plural
		    )
>


<!ELEMENT ArrayElements (Element*)>
<!ELEMENT Element (
		    ElementClass,
		    ArrayKeyForms
		    )
>

<!ELEMENT ArrayKeyForms (KeyFormID)*>

<!ELEMENT ComparisonOp (
		    CompOpName,
		    CompOpID,
		    CompOpDescription
		    )
>

<!ELEMENT Enumeration (
		    EnumerationID,
		    ArrayEnumerators
		    )
>

<!ELEMENT ArrayEnumerators (Enumerator)*>
<!ELEMENT Enumerator (
		    EnumeratorName,
		    EnumeratorID,
		    EnumeratorDescription
		    )
>

<!-- ==================================================================== -->
<!--                       Atomic elements                                -->
<!-- ==================================================================== -->
<!--Boolean-->
<!ELEMENT ChangeState (doesntChangeState|changesState)>
<!ELEMENT DirectParamIsReference (directParamIsValue|directParamIsReference)>
<!ELEMENT EnumIsExclusive (enumListCanRepeat|enumListIsExclusive)>
<!ELEMENT EnumsAreTypes (enumsAreConstants|enumsAreTypes)>
<!ELEMENT IsApostrophe (noApostrophe|apostrophe)>
<!ELEMENT IsEnumerated (notEnumerated|enumerated)>
<!ELEMENT IsFeminine (notFeminine|feminine)>
<!ELEMENT IsListOfItems (singleItem|listOfItems)>
<!ELEMENT IsMasculine (notMasculine|masculine)>
<!ELEMENT IsOptional (directParamRequired|directParamOptional)>
<!ELEMENT IsReadWrite (readOnly|readWrite)>
<!ELEMENT LabeledParam (prepositionParam|labeledParam)>
<!ELEMENT NonVerbEvent (verbEvent|nonVerbEvent)>
<!ELEMENT NotDirectParamIsTarget (directParamIsTarget|notDirectParamIsTarget)>
<!ELEMENT ParamIsReference (paramIsValue|paramIsReference)>
<!ELEMENT ParamIsTarget (notParamIsTarget|paramIsTarget)>
<!ELEMENT Plural (singular|plural)>
<!ELEMENT PropertyIsReference (propertyIsValue|propertyIsReference)>
<!ELEMENT ReplyIsReference (replyIsValue|replyIsReference)>
<!ELEMENT TightBindingFunction (notTightBindingFunction|tightBindingFunction)>


<!--String-->
<!ELEMENT ClassDescription (#PCDATA)>
<!ELEMENT CompOpDescription (#PCDATA)>
<!ELEMENT CompOpName (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT DirectParamDescription (#PCDATA)>
<!ELEMENT EnumeratorDescription (#PCDATA)>
<!ELEMENT EnumeratorName (#PCDATA)>
<!ELEMENT EventDescription (#PCDATA)>
<!ELEMENT EventName (#PCDATA)>
<!ELEMENT ParameterDescription (#PCDATA)>
<!ELEMENT ParameterName (#PCDATA)>
<!ELEMENT PropertyDescription (#PCDATA)>
<!ELEMENT PropertyName (#PCDATA)>
<!ELEMENT ReplyDescription (#PCDATA)>
<!ELEMENT SuiteName (#PCDATA)>
<!ELEMENT SuiteDescription (#PCDATA)>

<!--Four char codes-->
<!ELEMENT ClassID (#PCDATA)>
<!ELEMENT ElementClass (#PCDATA)>
<!ELEMENT CompOpID (#PCDATA)>
<!ELEMENT DirectParamType (#PCDATA)>
<!ELEMENT EnumerationID (#PCDATA)>
<!ELEMENT EnumeratorID (#PCDATA)>
<!ELEMENT EventClass (#PCDATA)>
<!ELEMENT EventID (#PCDATA)>
<!ELEMENT KeyFormID (#PCDATA)>
<!ELEMENT ParameterID (#PCDATA)>
<!ELEMENT ParameterType (#PCDATA)>
<!ELEMENT PropertyClass (#PCDATA)>
<!ELEMENT PropertyID (#PCDATA)>
<!ELEMENT ReplyType (#PCDATA)>
<!ELEMENT SuiteID (#PCDATA)>

<!--integer-->
<!ELEMENT LanguageCode (integer)>
<!ELEMENT ScriptCode (integer)>
<!ELEMENT SuiteLevel (integer)>
<!ELEMENT SuiteVersion (integer)>

<!--hex byte-->
<!ELEMENT MajorVersion (#PCDATA)>
<!ELEMENT MinorVersion (#PCDATA)>


<!ELEMENT Reserved EMPTY >
<!ELEMENT true EMPTY >
<!ELEMENT false EMPTY >
<!ELEMENT bool (true|false) >
<!ELEMENT integer (#PCDATA)>

<!--Flag values-->
<!ELEMENT enumListCanRepeat (false)>
<!ELEMENT doesntChangeState (false)>
<!ELEMENT directParamIsValue (false)>
<!ELEMENT enumsAreConstants (false)>
<!ELEMENT notTightBindingFunction (false)>
<!ELEMENT noApostrophe (false)>
<!ELEMENT notEnumerated (false)>
<!ELEMENT singleItem (false)>
<!ELEMENT directParamRequired (false)>
<!ELEMENT directParamIsTarget (false)>
<!ELEMENT notFeminine (false)>
<!ELEMENT notMasculine (false)>
<!ELEMENT notEnumerated (false)>
<!ELEMENT singleItem (false)>
<!ELEMENT required (false)>
<!ELEMENT notParamIsTarget (false)>
<!ELEMENT notEnumerated (false)>
<!ELEMENT singleItem (false)>
<!ELEMENT readOnly (false)>
<!ELEMENT notEnumerated (false)>
<!ELEMENT singleItem (false)>
<!ELEMENT replyRequired (false)>
<!ELEMENT verbEvent (false)>
<!ELEMENT paramIsValue (false)>
<!ELEMENT prepositionParam (false)>
<!ELEMENT propertyIsValue (false)>
<!ELEMENT replyIsValue (false)>
<!ELEMENT singular (false)>

<!ELEMENT enumListIsExclusive (true)>
<!ELEMENT changesState (true)>
<!ELEMENT directParamIsReference (true)>
<!ELEMENT enumsAreTypes (true)>
<!ELEMENT tightBindingFunction (true)>
<!ELEMENT apostrophe (true)>
<!ELEMENT enumerated (true)>
<!ELEMENT listOfItems (true)>
<!ELEMENT directParamOptional (true)>
<!ELEMENT notDirectParamIsTarget (true)>
<!ELEMENT feminine (true)>
<!ELEMENT masculine (true)>
<!ELEMENT enumerated (true)>
<!ELEMENT listOfItems (true)>
<!ELEMENT optional (true)>
<!ELEMENT paramIsTarget (true)>
<!ELEMENT enumerated (true)>
<!ELEMENT listOfItems (true)>
<!ELEMENT readWrite (true)>
<!ELEMENT enumerated (true)>
<!ELEMENT listOfItems (true)>
<!ELEMENT replyOptional (true)>
<!ELEMENT nonVerbEvent (true)>
<!ELEMENT paramIsReference (true)>
<!ELEMENT labeledParam (true)>
<!ELEMENT propertyIsReference (true)>
<!ELEMENT replyIsReference (true)>
<!ELEMENT plural (true)>

=== Kristine1975/Rezilla/RezillaExtras/Xml/aete_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This is a preliminary draft version! -->
<!DOCTYPE AeteResource SYSTEM "file://localhost/System/Library/DTDs/aete.dtd">

<AeteResource>
<AeteResID></AeteResID>
<AeteResTitle></AeteResTitle>

<MajorVersion></MajorVersion>
<MinorVersion></MinorVersion>
<LanguageCode></LanguageCode>
<ScriptCode></ScriptCode>

<ArraySuites>

	<Suite>
	
	<SuiteName></SuiteName>       	
	<SuiteDescription></SuiteDescription>	
	<SuiteID></SuiteID>         	
	<SuiteLevel></SuiteLevel>      	
	<SuiteVersion></SuiteVersion>
	
		<ArrayEvents>
			<Event>
				<EventName></EventName>
				<EventDescription></EventDescription>
				<EventClass></EventClass>
				<EventID></EventID>
				<ReplyType></ReplyType>
				<ReplyDescription></ReplyDescription>
				<ReplyFlags>
					<IsOptional> replyRequired replyOptional </IsOptional>
					<IsListOfItems> singleItem listOfItems </IsListOfItems>
					<IsEnumerated> notEnumerated enumerated </IsEnumerated>
					<TightBindingFunction> notTightBindingFunction tightBindingFunction </TightBindingFunction>
					<EnumsAreTypes> enumsAreConstants enumsAreTypes </EnumsAreTypes>
					<EnumIsExclusive> enumListCanRepeat enumListIsExclusive </EnumIsExclusive>
					<ReplyIsReference> replyIsValue replyIsReference </ReplyIsReference>
					<Reserved/>
					<Reserved/>
					<Reserved/>
					<Reserved/>
					<Reserved/>
					<NonVerbEvent> verbEvent nonVerbEvent </NonVerbEvent>
					<Reserved/>
					<Reserved/>
					<Reserved/>
				</ReplyFlags>
				<DirectParamType></DirectParamType>
				<DirectParamDescription></DirectParamDescription>
				<DirectFlags>
					<IsOptional> directParamRequired directParamOptional </IsOptional>
					<IsListOfItems> singleItem listOfItems </IsListOfItems>
					<IsEnumerated> notEnumerated enumerated </IsEnumerated>
					<ChangeState> doesntChangeState changesState </ChangeState>
					<EnumsAreTypes> enumsAreConstants enumsAreTypes </EnumsAreTypes>
					<EnumIsExclusive> enumListCanRepeat enumListIsExclusive </EnumIsExclusive>
					<DirectParamIsReference> directParamIsValue directParamIsReference </DirectParamIsReference>
					<NotDirectParamIsTarget> directParamIsTarget notDirectParamIsTarget </NotDirectParamIsTarget>
					<Reserved/>
					<Reserved/>
					<Reserved/>
					<Reserved/>
					<Reserved/>
					<Reserved/>
					<Reserved/>
					<Reserved/>
				</DirectFlags>
				<ArrayOtherParams>
					<Parameter>	
						<ParameterName></ParameterName>
						<ParameterID></ParameterID>
						<ParameterType></ParameterType>
						<ParameterDescription></ParameterDescription>
						<ParameterFlags>
							<IsOptional> required optional </IsOptional>
							<IsListOfItems> singleItem listOfItems </IsListOfItems>
							<IsEnumerated> notEnumerated enumerated </IsEnumerated>
							<Reserved/>
							<EnumsAreTypes> enumsAreConstants enumsAreTypes </EnumsAreTypes>
							<EnumIsExclusive> enumListCanRepeat enumListIsExclusive </EnumIsExclusive>
							<ParamIsReference> paramIsValue paramIsReference </ParamIsReference>
							<ParamIsTarget> notParamIsTarget paramIsTarget </ParamIsTarget>
							<Reserved/>
							<Reserved/>
							<Reserved/>
							<Reserved/>
							<LabeledParam> prepositionParam labeledParam </LabeledParam>
							<IsFeminine> notFeminine feminine </IsFeminine>
							<IsMasculine> notMasculine masculine </IsMasculine>
							<Plural> singular plural </Plural>
						</ParameterFlags>
					</Parameter>
				</ArrayOtherParams>
			</Event>
			
		</ArrayEvents>
		
		<ArrayClasses>
			<Class>
				<ClassName></ClassName>
				<ClassID></ClassID>
				<ClassDescription></ClassDescription>
				<ArrayProperties>
					<Property>
						<PropertyName></PropertyName>
						<PropertyID></PropertyID>
						<PropertyClass></PropertyClass>
						<PropertyDescription></PropertyDescription>
						<PropertyFlags>
							<Reserved/>
							<IsListOfItems> singleItem listOfItems </IsListOfItems>
							<IsEnumerated> notEnumerated enumerated </IsEnumerated>
							<IsReadWrite> readOnly readWrite </IsReadWrite>
							<EnumsAreTypes> enumsAreConstants enumsAreTypes </EnumsAreTypes>
							<EnumIsExclusive> enumListCanRepeat enumListIsExclusive </EnumIsExclusive>
							<PropertyIsReference> propertyIsValue propertyIsReference </PropertyIsReference>
							<Reserved/>
							<Reserved/>
							<Reserved/>
							<Reserved/>
							<Reserved/>
							<IsApostrophe> noApostrophe apostrophe </IsApostrophe>
							<IsFeminine> notFeminine feminine </IsFeminine>
							<IsMasculine> notMasculine masculine </IsMasculine>
							<Plural> singular plural </Plural>
						</PropertyFlags>
					</Property>
				</ArrayProperties>
				<ArrayElements>
					<Element>
						<ElementClass></ElementClass>
						<ArrayKeyForms>
							<KeyFormID></KeyFormID>
						</ArrayKeyForms>
					</Element>
				</ArrayElements>
			</Class>
			
		</ArrayClasses>
		
		<ArrayComparisonOps>
			<ComparisonOp>
				<CompOpName></CompOpName>
				<CompOpID></CompOpID>
				<CompOpDescription></CompOpDescription>
			</ComparisonOp>
			
		</ArrayComparisonOps>
		
		<ArrayEnumerations>
			<Enumeration>
			<EnumerationID></EnumerationID>
				<ArrayEnumerators>
					<Enumerator>
						<EnumeratorName></EnumeratorName>
						<EnumeratorID></EnumeratorID>
						<EnumeratorDescription></EnumeratorDescription>
					</Enumerator>
				</ArrayEnumerators>
			</Enumeration>
			
		</ArrayEnumerations>
		
	</Suite>
	
</ArraySuites>

</AeteResource>
